apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: axita2enq-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: axita2enq-python 
  name: axita2enq-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: axita2enq-python 
